# Site
repository: Conatuseus/Conatuseus.github.io
# favicon: images/favicon.ico

# Personal info
name: 사명기
title: 백엔드 개발자 지망생
email: conatuseus@gmail.com
website: https://velog.io/@conatuseus

# Social links
# twitter_username: facespics
github_username:  Conatuseus
# dribbble_username: jekyll
# facebook_username: MyungkiSa
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/conas.png
about_content: | # this will include new lines to allow paragraphs
  백엔드 개발자를 지망하며, 우아한테크코스의 백엔드 과정을 수료했습니다.

  우아한테크코스에서 페어 프로그래밍, 팀 프로젝트를 경험했습니다.

  OOP, TDD, 읽기 좋은 코드를 지향하며 테스트 코드 작성은 필수라고 생각합니다.

  알고리즘 문제 푸는 것을 좋아해서 [Baekjoon Online Judge](https://www.acmicpc.net/user/Conatuseus)에서 655문제(Kotlin: 370, Java: 160, C: 120)를 해결했습니다.

  공유 문화와 꾸준한 학습이 성장을 이끈다고 생각하여, [TIL](https://github.com/Conatuseus/TIL)과 [블로그](https://velog.io/@conatuseus)를 통해 정리하고 학습합니다.

  기술뿐 아니라 협업에 있어서도 함께하고 싶은 사람이 되기위하여 노력합니다.
  
  지속적인 회고를 통해, **어제보다 오늘 더 성장한 개발자를 지향**합니다.

# Skills Section
# project_title: Skills

# Opensource Section
# project_title: Opensource

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
